[
  {
    "name": "macos",
    "captures": ["Library not loaded: @rpath/libzstd.1.dylib"]
  },
  {
    "name": "rocm",
    "captures": ["The action has timed out."]
  },
  { 
    "name": "bazel",
    "captures": ["Process completed with exit code 2."]
  },
  { 
    "name": "distributed/_tensor/test_dtensor_ops",
    "captures": ["RuntimeError: distributed/_tensor/test_dtensor_ops failed! Received signal: SIGSEGV"]
  },
  {
    "name": "macos",
    "captures": ["ModuleNotFoundError: No module named 'sympy'"]
  },
  {
    "name": "linux",
    "captures": ["The runner has received a shutdown signal"]
  },
  {
    "name": "win",
    "captures": ["The process cannot access the file .+ because it is being used by another process"]
  },
  {
    "name": "macos",
    "captures": ["Failure: There is only .+ free space left in .+, which is less than the minimum requirement of"]
  },
  {
    "name": "macos",
    "captures": ["test_torchinductor_opinfo .+ Received signal: SIGSEGV"]
  },
  {
    "name": "win",
    "captures": ["The operation was canceled"]
  },
  {
    "name": "asan",
    "captures": ["ERROR: ld.so: object .+ from LD_PRELOAD cannot be preloaded \\(cannot open shared object file\\)"]
  },
  {
    "name": "linux",
    "captures": ["The process '/usr/bin/git' failed with exit code 1"]
  },
  {
    "name": "macos",
    "captures": ["File doesn't exist"]
  },
  {
    "name": "ghstack-mergeability-check",
    "captures": ["fatal: ambiguous argument 'origin/gh.*"]
  }
]
